add solution for 05-http-server-streams
js-tasks-ru/nodejs-20201020_viktor-shataev pull request #5
Opened 2020-11-07 11:40 UTC by shataev

2020-11-07 11:47 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-07 12:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- при попытке создания слишком большого файла - ошибка 413
- при попытке создания слишком большого файла - ошибка 413
- файл не должен оставаться на диске при обрыве соединения
```

2020-11-07 18:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
- при попытке создания слишком большого файла - ошибка 413
- при попытке создания слишком большого файла - ошибка 413
```

2020-11-08 05:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
- при попытке создания слишком большого файла - ошибка 413
- при попытке создания слишком большого файла - ошибка 413
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```

2020-11-08 13:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Чат на Koa.js
- сообщение должно быть доставлено всем подписчикам
- если нет сообщения - запро�� должен игнорироваться
```

2020-11-08 14:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Чат на Koa.js
+ сообщение должно быть доставлено всем подписчикам
- если нет сообщения - запрос должен игнорироваться
```

2020-11-08 14:37 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Чат на Koa.js
+ сообщение должно быть доставлено всем подписчикам
+ если нет сообщения - запрос должен игнорироваться
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-09 05:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-09 09:20 UTC, tadjik1 commented on 05-http-server-streams/01-file-server-get/server.js
> +				fs.readFile( filepath, function ( error, data ) {
в этой задаче мы должны отдавать файл через стримы (с помощью `fs.createReadStream`). решение через `fs.readFile` считывает весь файл в память целиком, что может привести к большим проблемам если файл будет большим, так как память сервера закончится и приложение вылетит с ошибкой.

2020-11-09 09:24 UTC, shataev commented on 05-http-server-streams/01-file-server-get/server.js
> +				fs.readFile( filepath, function ( error, data ) {
Понял,  Сергей, спасибо! Сейчас переделаю.

2020-11-09 09:29 UTC, tadjik1 requested changes
3 задачи решены абсолютно верно, а первые 2 надо немного доделать.

2020-11-09 09:31 UTC, tadjik1 commented on 05-http-server-streams/02-file-server-post/server.js
> +				fs.access( filepath, fs.constants.F_OK, ( error ) => {
лучше сразу начать писать в файл с помощью `fs.createWriteStream`, и ловить ошибку `EEXIST`, потому что в текущем подходе может возникнуть проблема, о которой я говорил в начале 3-го занятия.

2020-11-09 09:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-09 09:53 UTC, shataev commented on 05-http-server-streams/02-file-server-post/server.js
> +				fs.access( filepath, fs.constants.F_OK, ( error ) => {
Да, я вспомнил, вы конечно же правы! Отредактировал должным образом)

2020-11-09 09:59 UTC, tadjik1 approved these changes
всё отлично! 💯

2020-11-09 10:00 UTC, merged