add solution for 07-mongodb-mongoose 02-rest-api
js-tasks-ru/nodejs-20201020_viktor-shataev pull request #6
Opened 2020-11-12 18:45 UTC by shataev

2020-11-12 19:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-13 10:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Онлайн-магазин (товары и категории)
+ по запросу должен возвращаться список категорий
+ если товары есть в базе - должен вернуться массив с товарами
+ если товаров не найдено - должен возвращаться пустой массив
+ товары по существующей подкатегории
+ сервер должен в��рнуть ошибку если идентификатор невалидный
+ сервер должен вернуть статус 404
- сервер должен вернуть товар по его айди
```
```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
- стратегия должна возвращать ошибку если указан несуществующий email
- стратегия должна возвращать ошибку если указан неверный пароль
- стратегия должна возвращать объект пользователя если email и пароль верные
```

2020-11-13 10:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Онлайн-магазин (товары и категории)
+ по запросу должен возвращаться список категорий
+ если товары есть в базе - должен вернуться массив с товарами
+ если товаров не найдено - должен возвращаться пустой массив
+ товары по существующей подкатегории
+ сервер должен вернуть ошибку если идентификатор невалидный
+ сервер должен вернуть статус 404
+ сервер должен вернуть товар по его айди
```
```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
- стратегия должна возвращать ошибку если указан несуществующий email
- стратегия должна возвращать ошибку если указан неверный пароль
- стратегия должна возвращать объект пользователя если email и пароль верные
```

2020-11-14 13:54 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Онлайн-магазин (товары и категории)
+ по запросу должен возвращаться список категорий
+ если товары есть в базе - должен вернуться массив с товарами
+ если товаров не найдено - должен возвращаться пустой массив
+ товары по существующей подкатегории
+ сервер должен в��рнуть ошибку если идентификатор невалидный
+ сервер должен вернуть статус 404
+ сервер должен вернуть товар по его айди
```
```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
+ стратегия должна возвращать ошибку если указан несуществующий email
+ стратегия должна возвращать ошибку если указан неверный пароль
+ стратегия должна возвращать объект пользователя если email и пароль верные
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-14 17:10 UTC, tadjik1 commented on 08-authentication/01-local/libs/strategies/local.js
> +	async function ( email, password, done ) {
когда вы работаете с функциями, который принимают коллбэки добавляйте обязательно обработку ошибок, потому что koa о них ничего не знает - и потенциальная ошибка приведет к падению всего процесса nodejs.

2020-11-14 17:11 UTC, tadjik1 requested changes
@shataev  все отлично! хорошие решения. надо исправить лишь небольшой момент, связанный с обработкой ошибок.

2020-11-15 13:35 UTC, shataev commented on 08-authentication/01-local/libs/strategies/local.js
> +	async function ( email, password, done ) {
Сергей, спасибо за комментарий! Понял свой недочет, решение поправил, оберну сценарий колбэка в try/catch

2020-11-15 13:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-16 11:28 UTC, tadjik1 approved these changes
@shataev всё отлично! 👍

2020-11-16 11:29 UTC, merged