add facebook authentication
js-tasks-ru/nodejs-20201020_viktor-shataev pull request #7
Opened 2020-11-22 09:42 UTC by shataev

2020-11-22 13:45 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Использование социальных сетей для аутентификации пользователей
+ функция authenticate должна возвращать ошибку, если email не передаётся
+ функция authenticate должна создавать пользователя если его еще нет
+ функция authenticate выбрасывает ошибку если email невалидный
+ функция authenticate возвращает пользователя, который уже есть в базе
```
```diff
Работа с пользователем, сессии
+ для пользователя должна создаваться сессия
+ авторизационный заголовок должен корректно обрабатываться
+ время последнего захода должно обновиться
+ несуществующий токен должен приводить к ошибке
+ незалогиненный пользователь не может сделать запрос на /me
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-23 10:15 UTC, tadjik1 commented on 08-authentication/02-oauth/libs/strategies/authenticate.js
> +		try {
операция `await User.findOne( { email } );` тоже может завершиться ошибкой - её тоже нужно обернуть в `try/catch`.

2020-11-23 10:17 UTC, tadjik1 requested changes
@shataev в целом всё верно, надо поправить лишь небольшой момент, связанный с обработкой ошибок.

2020-11-24 18:44 UTC, shataev commented on 08-authentication/02-oauth/libs/strategies/authenticate.js
> +		try {
Понял и поправил, Сергей! После сегодняшнего вэбинара проблем с ошибками быть не должно, спасибо вам!

2020-11-24 20:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-25 19:34 UTC, tadjik1 approved these changes

2020-11-25 19:35 UTC, merged